---
title: "Wash Benefits internal R package vignette"
author: "Andrew Mertens"
date: "May 18, 2016"
output: 
  html_document:
    mode: selfcontained
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: united
    highlight: pygments
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Package Function Index
####washb_means
####washb_glm
####washb_prescreen
####washb_permute
####sandwichSE
####washb_ttest
####washb_mh
####washb_tmle
####design.matrix (internal)
 

#washb_means  
Calculate outcome means by treatment group and robust 95% confidence intervals  


#washb_glm  
Estimate the ITT comparison between two arms using generalized linear models with robust SEs for continuous or binary outcomes.  Adjusted estimates are possible.  


#washb_prescreen  
Pre-screen candidate adjustment covariates and select only those that are associated with the outcome (likelihood ratio test P<0.2) in a univariate association  


#washb_permute  
Conduct a permutation test using a Wilcoxon Signed Rank test statistic for two treatment arms conditional on randomization block  

#sandwichSE  
Compute robust standard errors that account for repeated measures within clusters  

#washb_ttest
Conduct a paired t-test for difference in means  


#washb_mh  
Estimate pooled prevalence ratios or differences using the Mantel-Haenszel estimator (stratified by matched pair)  


#washb_tmle

#design.matrix (internal)
automatic transform of a covariate data.frame with factors into one with indicator variables (and an ommitted category)  


 


 

 

 

 

 

 


 

